apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: payment-service-config
spec:
  tracing:
    samplingRate: '1'
    otel:
      endpointAddress: 'http://localhost:4318'
      isSecure: false
      protocol: 'http'
  metric:
    enabled: true
  accessControl:
    defaultAction: allow
    trustDomain: 'public'
